# This configuration has been generated by the Azure Terraform plugin which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

output "admin_password" {
  value       = random_password.admin_password.result
  sensitive   = true
  description = "Administrator password for the Windows VM"
}