# This configuration has been generated by the Azure Terraform plugin which utilizes Generative AI which may result in unintended or inaccurate configuration code. A human must validate that this configuration accomplishes the desired goal before applying the configuration.

variable "resource_group_name" {
  type    = string
  default = "midhun-test"
}

variable "location" {
  type    = string
  default = "centralindia"
}

variable "virtual_network_name" {
  type    = string
  default = "test-ci-mk"
}